### ISSUE TITLE
Missing closing parenthesis causing syntax error

### ISSUE THREAD

**Issue by maxshowarth** [MJeremy2017/Reinforcement-Learning-Implementation#6]
https://github.com/MJeremy2017/Reinforcement-Learning-Implementation/blob/7ef2f36e991141154d1bc0e9afd55d25d8b09238/GridWorld/gridWorld.py#L52

A closing parenthesis is missing on line 52 which causes a syntax error.

**Comment by MJeremy2017** [comment]
you are right, can submit a merge request
